### ISSUE TITLE
Frostbolt gcd bug

### ISSUE THREAD

**Issue by Buquoy** [voidzone/Gnosis#3]
Hi,
I upgraded Gnosis with the recent version (30th of July) and found a small bug. I have a GCD indicator (non casttime spells) set up and it always worked perfectly. But now for some reason it also shows a gcd of a Frostbolt cast. As far as I know, this is the only spell, that does this. (maybe because of the icicle mechanic?) It's not a huge bug, but it gets a bit annoying since you cast frostbolt a lot as a frost mage and I'm quite certain it's not supposed to do that or atleast it didn't do it before.
P.S. Thanks for the development of this addon, I like it very much.

**Comment by voidzone** [comment]
Duplicate of #2 
Unfortunately I don't have a fix at this time.
